USE `ProjectB`;
CREATE TABLE `Tag` (
  `TagId` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `TaskId` INT NOT NULL,
  `TagName` VARCHAR(150) NOT NULL,
  `CreateDatetime` TIMESTAMP NULL DEFAULT NULL,
  `CreateUserId` INT DEFAULT NULL,
  `UpdateDatetime` TIMESTAMP NULL DEFAULT NULL,
  `UpdateUserId` INT DEFAULT NULL,
  `IsDeleted` INT NOT NULL DEFAULT '0',
  CONSTRAINT fk_task_id
    FOREIGN KEY (TaskId)
    REFERENCES Task(TaskId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;